In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [11]:
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [14]:
a.dtype

dtype('int32')

In [15]:
a = np.array([1, 2, 3], dtype = "int16")
a.dtype

dtype('int16')

In [16]:
a.itemsize

2

In [17]:
a = np.array([1, 2, 3])
a.itemsize

4

In [18]:
b.itemsize

8

In [19]:
a.nbytes

12