In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
a.shape

(2, 7)

In [5]:
a[1, 5]

13

In [6]:
a[1, -2]

13

In [7]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
a[:, 2]

array([ 3, 10])

In [9]:
a[0, 1:6:2]

array([2, 4, 6])

In [11]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [12]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [13]:
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [18]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
b[0, 1, 1]

4

In [20]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [21]:
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
