In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
np.ones((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [10]:
np.full((2, 2), 99)

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [12]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [13]:
np.random.rand(4, 2)

array([[0.95104511, 0.30803701],
       [0.2753354 , 0.52911923],
       [0.808851  , 0.83501498],
       [0.59788468, 0.21376694]])

In [14]:
np.random.random_sample(a.shape)

array([[0.38441885, 0.72916096, 0.90096633, 0.39381545, 0.46790923,
        0.23285073, 0.82783767],
       [0.35019682, 0.78825675, 0.59683982, 0.71405014, 0.31683236,
        0.22721203, 0.19562435]])

In [16]:
np.random.randint(7, size = (3, 3))

array([[0, 3, 3],
       [0, 1, 5],
       [3, 4, 3]])

In [21]:
np.random.randint(4, 7, size = (3, 3))

array([[6, 4, 6],
       [4, 5, 5],
       [4, 5, 4]])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [30]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [32]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [31]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]
