In [1]:
import numpy as np

In [12]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [10]:
a += 2
print(a)

[3 4 5 6]


In [15]:
b = np.array([1, 0, 1, 0])
print(b)

[1 0 1 0]


In [16]:
a + b

array([2, 2, 4, 4])

In [17]:
a ** 2

array([ 1,  4,  9, 16])

In [18]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [23]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [24]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [26]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [27]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.min(stats)

1

In [29]:
np.max(stats)

6

In [30]:
np.min(stats, axis = 1)

array([1, 4])

In [31]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [32]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [33]:
np.max(stats, axis = 1)

array([3, 6])

In [34]:
np.sum(stats)

21

In [35]:
np.sum(stats, axis = 0)

array([5, 7, 9])