In [1]:
import numpy as np

In [2]:
# 1. create empty NumPy matrix
empty_array = np.array([])

In [3]:
# 2.1. create NumPy array with 3 columns and 3 rows
array3x3 = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
print(array3x3)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [4]:
# 2.2. get dimensions of this array (i.e. shape)
array3x3.shape

(3, 3)

In [5]:
# 2.3. create a random NumPy array with 3 columns and 3 rows
np.random.randint(1, 10, size = (3, 3))

array([[4, 7, 9],
       [7, 3, 7],
       [3, 7, 2]])

In [ ]:
# 3. create NumPy array with same dimensions (3x3) but concatenate them to and print out the shape:

In [6]:
# 3.1. 3x6 (columns x rows)
np.vstack([array3x3, array3x3])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [7]:
# 3.2. 6x3 (columns x rows)
np.hstack([array3x3, array3x3])

array([[1., 2., 3., 1., 2., 3.],
       [4., 5., 6., 4., 5., 6.],
       [7., 8., 9., 7., 8., 9.]])